x-common-build: &build-template
  dockerfile: Dockerfile

x-common-env: &common-env
  env_file:
    - .env.api
  volumes:
    - api:/api

services:
  api-gateway:
    ports:
      - "5000:5000"
    depends_on:
      user-api:
        condition: service_started
      subscription-api:
        condition: service_started
      audio-storage-api:
        condition: service_started
    build:
      context: ./api-gateway
      <<: *build-template
    <<: *common-env

  audio-storage-api:
    ports:
      - "8081:8081"
    build:
      context: ./audio-storage-api
      <<: *build-template
    <<: *common-env

  user-api:
    ports:
      - "7777:7777"
    build:
      context: ./user-api
      <<: *build-template
    <<: *common-env

  subscription-api:
    ports:
      - "4444:4444"
    environment:
      - STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key
      - FRONTEND_SUCCESS_URL=http://localhost:3000/success
      - FRONTEND_CANCEL_URL=http://localhost:3000/cancel
    build:
      context: ./subscription-api
      <<: *build-template
    <<: *common-env

volumes:
  api:
