x-common-build: &build-template
  dockerfile: Dockerfile

x-common-env: &common-env
  volumes:
    - ui:/ui
  env_file:
    - .env.UI

services:
  subscription-ui:
    ports:
      - "4000:3000"
    build:
      context: ./subscription-ui
      <<: *build-template
    <<: *common-env

  audio-storage-ui:
    ports:
      - "3001:3000"
    build:
      context: ./audio-storage-ui
      <<: *build-template
    <<: *common-env

  user-ui:
    ports:
      - "7000:3000"
    build:
      context: ./user-ui
      <<: *build-template
    <<: *common-env

volumes:
  ui:


