x-common-build: &build-template
  dockerfile: Dockerfile

x-common-env: &common-env
  env_file:
    - .env.UI

services:
  subscription-ui:
    volumes:
      - subscription:/subscription
    ports:
      - "4000:3000"
    build:
      context: ./subscription-ui
      <<: *build-template
    <<: *common-env

  audio-storage-ui:
    valumes:
      - audio_storage:/audio_storage
    ports:
      - "3001:3000"
    build:
      context: ./audio-storage-ui
      <<: *build-template
    <<: *common-env

  user-ui:
    ports:
      - "7000:3000"
    volumes:
      - user:/user
    build:
      context: ./user-ui
      <<: *build-template
    <<: *common-env

volumes:
  audio_storage:
  subscription:
  user:
