version: '3.8'

services:
  # app-shell-ui:
  #   build:
  #     context: ./app-shell-ui
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3003:3000"
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost:3003" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   depends_on:
  #     ph-audio-storage-api:
  #       condition: service_started
  # config-server:
  #   image: springcloud/configserver
  #   ports:
  #     - "8888:8888"
  #   environment:
  #     - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/your-config-repo
  #     - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=main
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  # eureka-server:
  #   image: springcloud/eureka
  #   ports:
  #     - "8761:8761"
  #   depends_on:
  #     config-server:
  #       condition: service_healthy
  #   environment:
  #     - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - localstack_data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

  ph-audio-storage-api:
    build:
      context: ./ph-audio-storage-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - AWS_ACCESS_KEY=test
      - AWS_SECRET_KEY=test
      - AWS_REGION=us-east-2
      - AWS_S3_BUCKET=mikedevportfolio
      - STORAGE_TYPE=s3
    volumes:
      - audio_storage:/audio-storage
    depends_on:
      postgres:
        condition: service_healthy
      # localstack:
      #   condition: service_started

  ph-project-storage-api:
    image: ph-project-storage-api:latest
    ports:
      - "8082:8081"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - AWS_ACCESS_KEY=test
      - AWS_SECRET_KEY=test
      - AWS_REGION=us-east-2
      - AWS_S3_BUCKET=mikedevportfolio
      - STORAGE_TYPE=s3
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_FLYWAY_ENABLED=false
    volumes:
      - project_storage:/project-storage
    depends_on:
      postgres:
        condition: service_healthy
      # config-server:
      #   condition: service_healthy
      # eureka-server:
      #   condition: service_healthy
      # localstack:
      #   condition: service_started

volumes:
  postgres_data:
  localstack_data:
  audio_storage:
  project_storage:
