server:
  port: 8081

spring:
  application:
    name: audio-storage-api

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5332/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        ddl-auto: validate
        format-sql: true
      show-sql: true
    main:
      web-development-type: servlet
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      storeAudio:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      loadAudio:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      deleteAudio:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      storeAudio:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

storage:
  type: s3
  location: mikedevportfolio

cloud:
  aws:
    credentials:
      access-key: AKIARHQBNICKIZKZPQWX
      secret-key: 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
    region:
      static: ${AWS_REGION:us-east-2}
    s3:
      bucket: mikedevportfolio

audio:
  base:
    url: http://localhost:8081

logging:
  level:
    com.postgres: DEBUG
    org.springframework.data: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG