server:
  port: 8081

spring:
  application:
    name: project-storage-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_projects
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
#flyway:
#  enabled: true
#  baseline-on-migrate: true
#  locations: classpath:db/migration